"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/things3_to_kanban.py']
DATA_FILES = ['resources']
OPTIONS = {
        'iconfile':'resources/icon.icns',
        'plist': {'CFBundleShortVersionString':'1.0.0',}
}

setup(
    app=APP,
    name='KanbanView',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
